In [9]:
import fun
import os
from RBFNN import RBFNN
import numpy as np
from sklearn.model_selection import train_test_split

output_dir = "Data/Kelas 1 40"
slice_cols = 5
slice_rows = 3
margin_x = 50
margin_y = 78
pixel = (35,35)

In [10]:

# buat kotak utama
# file_names = [file for file in os.listdir(path) if os.path.isfile(os.path.join(path, file))]

# for file in file_names:
#     fun.crop_largest_box(f"{path}/{file}", file, output_dir_raw)


# potong kotak
# file_names = [file for file in os.listdir(output_dir_raw) if os.path.isfile(os.path.join(output_dir_raw, file))]

# for index, file in enumerate(file_names):
#     if index == 5:
#         break
#     fun.slice_image_with_margin(f"{output_dir_raw}/{file}", index, output_dir, slice_cols, slice_rows, margin_x, margin_y, pixel)


In [11]:


file_names = [file for file in os.listdir(output_dir) if os.path.isfile(os.path.join(output_dir, file))]
print(file_names, len(file_names))

# file1 = file_names[0]

# x = fun.load_pixel(f"{output_dir}/{file1}")


# Inisialisasi array untuk menyimpan semua data gambar
X = []  # Menyimpan fitur
y = []  # Menyimpan label (jika ada)

# Loop melalui semua file
for file_name in file_names:
    # Load pixel gambar (sudah dinormalisasi)
    img_data = fun.load_pixel(f"{output_dir}/{file_name}")
    
    # Tambahkan ke array X
    X.append(img_data)
    
    # Jika ingin membuat label (contoh: ambil dari nama file)
    # Contoh: jika format nama file "class1_image1.png"
    label = file_name.split("_")[0]  # Ambil bagian kelas
    y.append(label)

['0_1.png', '0_10.png', '0_11.png', '0_12.png', '0_13.png', '0_14.png', '0_15.png', '0_16.png', '0_17.png', '0_18.png', '0_19.png', '0_2.png', '0_20.png', '0_21.png', '0_22.png', '0_23.png', '0_24.png', '0_25.png', '0_26.png', '0_27.png', '0_28.png', '0_29.png', '0_3.png', '0_30.png', '0_31.png', '0_32.png', '0_33.png', '0_34.png', '0_35.png', '0_36.png', '0_37.png', '0_38.png', '0_39.png', '0_4.png', '0_5.png', '0_6.png', '0_7.png', '0_8.png', '0_9.png', '1_1.png', '1_10.png', '1_11.png', '1_12.png', '1_13.png', '1_14.png', '1_15.png', '1_16.png', '1_17.png', '1_18.png', '1_19.png', '1_2.png', '1_20.png', '1_21.png', '1_22.png', '1_23.png', '1_24.png', '1_25.png', '1_26.png', '1_27.png', '1_28.png', '1_29.png', '1_3.png', '1_30.png', '1_31.png', '1_32.png', '1_33.png', '1_34.png', '1_35.png', '1_36.png', '1_37.png', '1_38.png', '1_39.png', '1_4.png', '1_5.png', '1_6.png', '1_7.png', '1_8.png', '1_9.png', '2_1.png', '2_10.png', '2_11.png', '2_12.png', '2_13.png', '2_14.png', '2_15.png'

In [12]:
# m = (pixel[0] * pixel[1]) / 4 + (pixel[0] * pixel[1])
# print(m)
# print(x[:20])


In [14]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)


X = np.array(X)
y = np.array(y) 

print(X)
print(y)

# Inisialisasi dan training model
rbf = RBFNN(n_centers=15)
rbf.fit(X_train, y_train)

y_pred = rbf.predict(X_test)
# Prediksi
test_image = np.random.rand(1225)  # Gambar uji 35x35
prediction = rbf.predict([test_image])
print("Prediksi:", prediction)

[[0.96862745 0.96470588 0.96078431 ... 0.98823529 0.98823529 0.98823529]
 [0.96862745 0.96862745 0.96862745 ... 0.99215686 0.99215686 0.99215686]
 [0.95686275 0.95686275 0.96078431 ... 0.99607843 0.99215686 0.99215686]
 ...
 [0.96862745 0.96862745 0.96470588 ... 0.97254902 0.97647059 0.97647059]
 [0.97254902 0.97254902 0.97254902 ... 0.98039216 0.98039216 0.98039216]
 [0.97254902 0.97647059 0.96862745 ... 0.97647059 0.98039216 0.98039216]]
['0' '0' '0' '0' '0' '0' '0' '0' '0' '0' '0' '0' '0' '0' '0' '0' '0' '0'
 '0' '0' '0' '0' '0' '0' '0' '0' '0' '0' '0' '0' '0' '0' '0' '0' '0' '0'
 '0' '0' '0' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1'
 '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1'
 '1' '1' '1' '1' '1' '1' '2' '2' '2' '2' '2' '2' '2' '2' '2' '2' '2' '2'
 '2' '2' '2' '2' '2' '2' '2' '2' '2' '2' '2' '2' '2' '2' '2' '2' '2' '2'
 '2' '2' '2' '2' '2' '2' '2' '2' '2' '3' '3' '3' '3' '3' '3' '3' '3' '3'
 '3' '3' '3' '3' '3' '3' '3' '3' '3' '3' '3' 

UFuncTypeError: ufunc 'matmul' did not contain a loop with signature matching types (dtype('float64'), dtype('<U14')) -> None